AWSTemplateFormatVersion: 2010-09-09

Description: |
  This is the web Apache HTTP server. Creating EC2 instance with a 
  user data that installs Apache web server.

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the keypair
  MySecurityGroup:
    Description: Security group
    Type: AWS::EC2::SecurityGroup::GroupName

Resources:
  CaruselWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e731c8a588258d0d
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: CloudformationWebServer
      UserData: 
        Fn::Base64: |
            #!/bin/bash
            dnf update -y
            dnf install git httpd -y
            git clone https://github.com/able-im/carousel-static-website-ec2-CF.git /home/ec2-user/app
            mv /home/ec2-user/app/static-web/* /var/www/html
            systemctl start httpd
            systemctl enable httpd              

Outputs:
  PublicIPAddress:
    Description: The public IP of my instance
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt CaruselWebServer.PublicIp
